# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  lane :install_pods do
    cocoapods
  end

  lane :update_pods do
    cocoapods(
      command: 'update',
      repo_update: true
    )
  end

  lane :enable_test_coverage do
    # Set the build setting for code coverage
    sh("xcodebuild -project nimble.xcodeproj -scheme Nimble -enableCodeCoverage YES clean build test")
  end
end

